### ISSUE TITLE
Theming: couldn't find custom class

### ISSUE THREAD

**Issue by nikotaf** [sameer-shelavale/multi-captcha#31]
There must be something wrong in ```Captcha.php``` @ line 166. Shouldn't the ```$themeName``` class be under the ```Multicaptcha\Themes``` namespace? I'm having a hard time loading a custom theme and apply it. Could you provide some help on how to load ```$themeName``` under ```Multicaptcha\Themes``` namespace and not just ```Multicaptcha```? Thanks in advance.

**Comment by sameer-shelavale** [comment]
@nikotaf you can pass namespaced theme class name in the theme parameter as well
e.g 
`'theme' => '\nikotaf\CustomTheme1'`
if your theme is not namespaced then you can use
`'theme' => '\CustomTheme1'`
let me know if this resolves your issue

**Comment by nikotaf** [comment]
Thank you for replying.
As it seems, I was stuck at very simple issue. Here is  why:

```Captcha.php``` file is under ```Multicaptcha``` namespace.

Using ```DefaultTheme.php``` as a guideline, I changed the class name to ```customTheme```, and copied the file to ```customTheme.php``` inside ```themes``` folder. Themes are under ```MultiCaptcha\Themes``` namespace.

Using ```'theme' => 'customTheme'``` in options doesn't work.

Tweaking ```Captcha.php``` line 164
```echo $themeName . "<br/>" . (class_exists( $themeName )?"TRUE":"FALSE");```

I get

```customTheme```
```FALSE```

which is ok since ```Captcha.php``` is under ```Multicaptcha``` namespace, script was looking for ```Multicaptcha\customTheme``` class, which does not exists.

**But**, with your suggestion to set in options the namespace, which is quite reasonable, I have:
```'theme' => 'Themes\customTheme'```
which should be resolved in ```Captcha.php``` to ```Multicaptcha\Themes\customTheme```

Instead, I get:

```Themes\customTheme```
```FALSE```

I finaly got the desired result by setting options with
```'theme' => 'Multicaptcha\Themes\customTheme'```
which is resolved correctly in ```Captcha.php``` since it's full namespace, but it should work by simply
```'theme' => 'customTheme'```
since theme files are under ```MultiCaptcha\Themes``` namespace.

I hope these make sense. Have I lost something somewhere? Why a simple ```'theme' => 'customTheme'``` does not work, since both default and my custom theme are under same namespace?

Again thanks for your help.

**Comment by sameer-shelavale** [comment]
@nikotaf 
`'theme' => 'customTheme'`  does not work because we are using `class_exists( $themeName ) ` on line number 165 in Captcha.php
This function [class_exists()](http://php.net/manual/en/function.class-exists.php) returns _false_ when using the short, aliased class name - 
So whenever a class name is used as string, only the full-namespaced version should be used.

**Comment by nikotaf** [comment]
@sameer-shelavale
So the only way a custom theme be functional (and visible by the script) is to be set in options with full namespace. Thank you again for your help and clarification.
